### ISSUE TITLE
Error running on arm arhitecture

### ISSUE THREAD

**Issue by mihazg99** [situmtech/flutter#89]
Swift Compiler Error (Xcode): Could not find module 'SitumWayfinding' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, at: 

Although it can be run trough Rosseta it would be nice to fix this issue by supporting arm.

**Comment by Kurak5** [comment]
I have the same problem. Unfortunately, running through Rosetta doesn't work for me.
@mihazg99  did you do any additional configuration to open via Rosetta? I've tried excluding arm64 architecture, cleannig pods, cleaning build folder, restarting XCode but still the same error.

**Comment by mihazg99** [comment]
@Kurak5 No, I haven't done any addition configuration except running trough Rossetta.
